/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoicemapper.ui;

import invoicemapper.dal.AgentDataService;
import invoicemapper.dal.ClientDataService;
import invoicemapper.dal.InvoiceDataService;
import invoicemapper.dal.SaleDataService;
import invoicemapper.lib.Agent;
import invoicemapper.lib.Client;
import invoicemapper.lib.Invoice;
import invoicemapper.lib.Sale;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author johnk
 */
public class InvoiceReportUI extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceReportUI
     */
      private ArrayList<Client> clients;
    private ClientDataService clientDataService;
    private InvoiceDataService invoiceDataService;
    private SaleDataService saleDataService;

    /**
     * Creates new form AgentSalesReportUI
     */
    public InvoiceReportUI() throws SQLException {
        initComponents();

        clientDataService = new ClientDataService();
        clients = new ArrayList<Client>();

        invoiceDataService = new InvoiceDataService();
        saleDataService = new SaleDataService();

        fetchClients();
        fetchInvoicesForSelectedClient();
    }
    
     public void fetchClients() throws SQLException {
        clients = clientDataService.GetAll();

        DefaultComboBoxModel dml = new DefaultComboBoxModel();
        for (int i = 0; i < clients.size(); i++) {
            dml.addElement(clients.get(i).getName());
        }

        clientSelect.setModel(dml);
    }

    public void fetchInvoicesForSelectedClient() throws SQLException {
        String selectedClient = String.valueOf(clientSelect.getSelectedItem());

        ArrayList<Invoice> clientInvoices = invoiceDataService.GetByClient(selectedClient);

        DefaultListModel listModel = new DefaultListModel();

        for (Invoice a : clientInvoices) {
            listModel.addElement(String.valueOf(a.getDate()));
        }

        invoiceListBox.setModel(listModel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNonPayable = new javax.swing.JLabel();
        clientSelect = new javax.swing.JComboBox<>();
        lblPayable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblChargebacks = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceListBox = new javax.swing.JList<>();
        lblCommissions = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Commissions:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Invoice Report");

        lblTotalSales.setText("0");

        jLabel2.setText("Client");

        lblNonPayable.setText("0");

        clientSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientSelectActionPerformed(evt);
            }
        });

        lblPayable.setText("0");

        jLabel3.setText("Invoice");

        lblChargebacks.setText("0");

        invoiceListBox.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        invoiceListBox.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                invoiceListBoxValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(invoiceListBox);

        lblCommissions.setText("0");

        jLabel4.setText("Total Sales:");

        jLabel5.setText("Payable:");

        jLabel6.setText("Non Payable:");

        jLabel7.setText("Chargebacks:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCommissions, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChargebacks, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNonPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clientSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblTotalSales))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblPayable))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblNonPayable))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblChargebacks))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblCommissions))))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new MainUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void clientSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSelectActionPerformed
        
        lblTotalSales.setText("0");
        lblPayable.setText("0");
        lblNonPayable.setText("0");
        lblChargebacks.setText("0");
        lblCommissions.setText("0");
        
        try {
            fetchInvoicesForSelectedClient();
        } catch (SQLException ex) {
            Logger.getLogger(ManageAgentsUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clientSelectActionPerformed

    private void invoiceListBoxValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_invoiceListBoxValueChanged
        Date invoiceDate  = null;
          try {
              invoiceDate = new SimpleDateFormat("yyyy-MM-dd").parse(invoiceListBox.getSelectedValue());
          } catch (ParseException ex) {
              Logger.getLogger(InvoiceReportUI.class.getName()).log(Level.SEVERE, null, ex);
          }
        String selectedClient = String.valueOf(clientSelect.getSelectedItem());

        if (invoiceDate != null) {

            ArrayList<Sale> invoiceSales = new ArrayList<Sale>();
            try {
                invoiceSales = saleDataService.GetByInvoice(selectedClient, invoiceDate);
            } catch (SQLException ex) {
                Logger.getLogger(AgentSalesReportUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            int totalChargebacks = 0;
            int totalPayable = 0;
            int totalNonPayable = 0;
            int totalSales = 0;
            float totalCommissions = 0;

            for (Sale s : invoiceSales) {
                totalSales++;
                totalCommissions+= s.getCommission();

                if (s.isChargeback()) {
                    totalChargebacks ++;
                }
                else {
                    if (s.isPayable()) {
                        totalPayable++;
                    } else {
                        totalNonPayable++;
                    }
                }
            }

            lblTotalSales.setText(String.valueOf(totalSales));
            lblPayable.setText(String.valueOf(totalPayable));
            lblNonPayable.setText(String.valueOf(totalNonPayable));
            lblChargebacks.setText(String.valueOf(totalChargebacks));
            lblCommissions.setText(String.valueOf(totalCommissions));
        }
    }//GEN-LAST:event_invoiceListBoxValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InvoiceReportUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InvoiceReportUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> clientSelect;
    private javax.swing.JList<String> invoiceListBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChargebacks;
    private javax.swing.JLabel lblCommissions;
    private javax.swing.JLabel lblNonPayable;
    private javax.swing.JLabel lblPayable;
    private javax.swing.JLabel lblTotalSales;
    // End of variables declaration//GEN-END:variables
}
